### ISSUE TITLE
slack-api gem をなくす

### ISSUE THREAD

**Issue by hakatashi** [tsg-ut/slack-patron#26]
slack-patronが依存している[slack-api](https://rubygems.org/gems/slack-api/versions/1.2.3?locale=ja)はすでに2018年に開発が停止しており、Ruby 3.0以降で動かない。[slack-ruby-client](https://github.com/slack-ruby/slack-ruby-client)などに移行する必要がある。

**Comment by cookie-s** [comment]
うーん、slack-ruby-clientは、RTMを普通に使いますね　Events APIには対応しているが、SocketModeには対応してなさそうな雰囲気
https://github.com/slack-ruby/slack-ruby-client/blob/72f7e15cd3aaf5d68dd8a678e51e07dbb2fdc454/lib/slack/real_time/client.rb#L183-L191

**Comment by cookie-s** [comment]
まあslack-ruby-clientのEvents APIにするんかなぁ

**Comment by cookie-s** [comment]
やるかー

**Comment by hakatashi** [comment]
天才 現人神 強力粉

**Comment by cookie-s** [comment]
気づいたんですが、legacy appのbot tokenは、bot scopeをもっているんですが、bot scopeのtokenではemoji.list methodはpermission不足で呼べない。なので、update_emojisは今動いてない。

**Comment by cookie-s** [comment]
消しちゃおっかな

**Comment by cookie-s** [comment]
んーでもmongoにはいってるのはなんなんだろ

**Comment by cookie-s** [comment]
ENABLE_PRIVATE_CHANNELとENABLE_DIRECT_MESSAGEの機能切っていいですか？group/imじゃなくてconversationsに統一された話が大分前にあって、かなりめんどい

**Comment by cookie-s** [comment]
conversations.historyも呼べないじゃん

**Comment by cookie-s** [comment]
* Legacy AppのBot tokenの場合、
  * conversations.historyが呼べない
    * たぶんupdateしたら呼べるようになる、そうすると、起動時のちょっと過去データも読めるようになる
  * emoji.listが呼べない
    * たぶんupdateしたら呼べるようになる、ただ、今もmongoに少し古い時点のデータが保存されており、経路が謎 @hakatashi がなんかやってるような気がする


* channel/group/imがconversationsに過去に統一されており、group/imをサポートするのがちょっとめんどくさい
  * 使ってるひとがいるんならサポートしてやってもいいが？
