### ISSUE TITLE
RTM API をやめる

### ISSUE THREAD

**Issue by hakatashi** [tsg-ut/slack-patron#27]
> What isn't changing
> Existing apps and integrations may continue using the RTM API. With few ways remaining to connect to the [RTM API](https://api.slack.com/rtm), we strongly recommend you consider alternatives ([like Socket Mode](https://api.slack.com/changelog/2021-10-rtm-start-to-stop#events-sockets)) even if you already use rtm.connect.

https://api.slack.com/changelog/2021-10-rtm-start-to-stop

**Comment by cookie-s** [comment]
タイトルとリミット、ちょっとミスリーディングじゃない？

**Comment by cookie-s** [comment]
rtm.startがこわれるだけ

**Comment by hakatashi** [comment]
Editしていいよ

**Comment by cookie-s** [comment]
いまお布団だから今度

**Comment by cookie-s** [comment]
Editした

**Comment by cookie-s** [comment]
今使ってるライブラリ
https://rubygems.org/gems/slack-api
https://github.com/aki017/slack-ruby-gem

**Comment by cookie-s** [comment]
なるほど #26 があるのか

**Comment by cookie-s** [comment]
やるか
