### ISSUE TITLE
メッセージ中のチャンネル名をみやすく

### ISSUE THREAD

**Issue by pizzacat83** [tsg-ut/slack-patron#5]
現状: `<#CXXXXXXXX|#sandbox>`
これを `<#sandbox>` にしたい

あとbotの投稿だと `<#CXXXXXXXX>` という形式をしている場合があって，この場合もちゃんと 
 `<#sandbox>` と表示したい

プレーンテキストでも十分嬉しいが，チャンネルへのリンクになると大変クオリティが高い

**Comment by hakatashi** [comment]
<!channel>

**Comment by hakatashi** [comment]
解決済み
