### ISSUE TITLE
謎のホワイトアウト

### ISSUE THREAD

**Issue by JP3BGY** [tsg-ut/slack-patron#57]
再現方法(TSGerのみ)
https://slack-log.tsg.ne.jp/C7AAX50QY/1611719683.107300
多分周辺におかしいメッセージがある。

**Comment by moratorium08** [comment]
Block KitのSectionに対応する概念である SectionBlock コンポーネントの描画の際に、textが必ず存在していることを仮定しているが、これは誤り。 https://github.com/tsg-ut/slack-patron/blob/master/viewer/front/components/message/Block.js#L163-L176

https://api.slack.com/reference/block-kit/blocks#section
> The text for the block, in the form of a text object. Minimum length for the text in this field is 1 and maximum length is 3000 characters. This field is not required if a valid array of fields objects is provided instead.

この描画処理において、textがundefinedの場合には、描画をスキップすると良いと思われる。
```jsx
    {text && (
      <div className="section-block-text">
        <Text text={text} />
      </div>
    )}
```
